# Generated by Django 5.1 on 2024-09-06 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_users_groups_users_is_active_users_is_staff_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
    ]
