# Generated by Django 5.1 on 2024-09-29 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='found_items',
            name='img',
        ),
    ]
