# Generated by Django 5.1 on 2024-09-29 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_found_items_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='found_items',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='found_items',
            name='user',
        ),
    ]
