# Generated by Django 5.1 on 2024-09-29 08:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_found_items_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='found_items',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
