# Generated by Django 5.1 on 2024-09-29 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_found_items_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='found_items',
            name='img',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
    ]
