# Generated by Django 5.1 on 2024-09-29 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_found_items_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='found_items',
            old_name='user',
            new_name='username',
        ),
    ]
